import { auth, db } from './firebase-config.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js';
import { collection, getDocs, query, where } from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js';
import { MAINTENANCE_RULES, classifyMotorcycleCategory } from './maintenanceOptions.js';
import { normalizeRecord } from './utils-module.js';

const STREAK_PREFIX = 'motocare-streak-v1:';
function dateValue(value) { if (value && typeof value.toDate === 'function') return value.toDate(); const date = value instanceof Date ? value : new Date(value); return Number.isNaN(date.getTime()) ? null : date; }
function dateKey(date = new Date()) { return date.toISOString().slice(0, 10); }
function formatDate(date) { return date ? date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : 'Date not set'; }
function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character])); }
function motorcycleName(motorcycle = {}) { return motorcycle.motorcycleName || [motorcycle.brand, motorcycle.model].filter(Boolean).join(' ') || 'Motorcycle'; }
function mileage(motorcycle = {}) { const value = Number(motorcycle.mileage ?? motorcycle.odo ?? motorcycle.currentOdo ?? motorcycle.odometer ?? 0); return Number.isFinite(value) ? value : 0; }
function completion(record = {}) { const status = String(record.status || '').toLowerCase(); return status === 'completed' || status === 'complete' || status === 'done' || Boolean(record.completedAt || record.completedMileage || record.date); }
function latestCompletion(records, motorcycleId, rule) { return records.filter((record) => { if (String(record.motorcycleId || '') !== String(motorcycleId) || !completion(record)) return false; const task = String(record.task || record.title || record.name || '').toLowerCase(); return record.taskKey === rule.key || task.includes(String(rule.task).toLowerCase()) || String(rule.task).toLowerCase().includes(task); }).sort((a, b) => (dateValue(b.completedAt || b.date || b.createdAt)?.getTime() || 0) - (dateValue(a.completedAt || a.date || a.createdAt)?.getTime() || 0))[0]; }
function buildMaintenanceItems(motorcycles, records) { return motorcycles.flatMap((motorcycle) => { const category = classifyMotorcycleCategory(motorcycle); const rules = MAINTENANCE_RULES[category.key] || []; const currentMileage = mileage(motorcycle); return rules.map((rule) => { const record = latestCompletion(records, motorcycle.id, rule); const anchor = Number(record?.completedMileage ?? record?.mileage ?? currentMileage); const interval = Number(rule.interval || 0); const dueMileage = record ? anchor + interval : Math.ceil(currentMileage / Math.max(1, interval)) * interval; const explicitDate = dateValue(record?.nextDueDate || record?.dueDate); const daysUntil = explicitDate ? Math.ceil((explicitDate - new Date()) / 86400000) : Math.ceil((dueMileage - currentMileage) / Math.max(1, currentMileage / 30)); const status = daysUntil < 0 ? 'overdue' : daysUntil <= 14 ? 'due-soon' : 'scheduled'; return { id: `${motorcycle.id}-${rule.key}`, task: rule.task, icon: rule.icon || 'wrench', motorcycleName: motorcycleName(motorcycle), dueDate: explicitDate, dueMileage, daysUntil, status }; }); }).sort((a, b) => a.daysUntil - b.daysUntil); }
function renderStreak(uid) { let data = {}; try { data = JSON.parse(localStorage.getItem(`${STREAK_PREFIX}${uid}`)) || {}; } catch { data = {}; } const dates = new Set(data.dates || []); let streak = dates.has(dateKey()) ? 1 : 0; const cursor = new Date(); while (streak > 0) { cursor.setDate(cursor.getDate() - 1); if (!dates.has(dateKey(cursor))) break; streak += 1; } document.getElementById('streakCount').textContent = `${streak}-Day Streak`; }
function renderUrgent(items) { const container = document.getElementById('urgentMaintenanceList'); if (!items.length) { container.innerHTML = '<p class="rounded-xl bg-white p-4 text-xs text-gray-500 shadow-sm">No urgent maintenance items.</p>'; return; } container.innerHTML = items.map((item) => `<a href="schedule.html" class="dashboard-list-row flex items-center gap-3 rounded-xl border border-gray-100 bg-white px-3 shadow-sm"><span class="dashboard-icon ${item.status === 'overdue' ? 'bg-red-50 text-red-600' : 'bg-amber-50 text-amber-600'}"><i class="lucide lucide-${escapeHtml(item.icon)}" aria-hidden="true"></i></span><span class="min-w-0 flex-1"><span class="flex items-center gap-2"><strong class="truncate text-xs">${escapeHtml(item.task)}</strong><em class="rounded-full ${item.status === 'overdue' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'} px-2 py-1 text-[8px] font-bold not-italic">${item.status === 'overdue' ? 'Overdue' : 'Due Soon'}</em></span><small class="block truncate text-[9px] text-gray-500">${escapeHtml(item.motorcycleName)} · ${item.dueDate ? formatDate(item.dueDate) : `Due at ${item.dueMileage.toLocaleString()} km`}</small></span><i class="lucide lucide-chevron-right text-gray-300" aria-hidden="true"></i></a>`).join(''); }
function renderRecent(records) { const container = document.getElementById('recentRecordsList'); const items = records.sort((a, b) => (dateValue(b.date || b.createdAt)?.getTime() || 0) - (dateValue(a.date || a.createdAt)?.getTime() || 0)).slice(0, 5); if (!items.length) { container.innerHTML = '<p class="p-4 text-xs text-gray-500">No recent records.</p>'; return; } container.innerHTML = items.map((item) => `<a href="history.html" class="dashboard-list-row flex items-center gap-3 border-b border-gray-100 px-3 last:border-0"><span class="dashboard-icon bg-green-50 text-green-700"><i class="lucide lucide-wrench" aria-hidden="true"></i></span><span class="min-w-0 flex-1"><strong class="block truncate text-xs">${escapeHtml(item.title || item.task || 'Service record')}</strong><small class="block truncate text-[9px] text-gray-500">${escapeHtml(item.motorcycleName || item.motorcycle || 'Motorcycle')} · ${formatDate(dateValue(item.date || item.createdAt))}</small></span><strong class="text-xs text-gray-700">&#8369;${Number(item.cost ?? item.amount ?? 0).toLocaleString()}</strong></a>`).join(''); }
function renderInsight(motorcycles) { const bike = motorcycles[0]; const averageMileage = motorcycles.length ? Math.round(motorcycles.reduce((sum, item) => sum + mileage(item), 0) / motorcycles.length / 30) : 0; const category = bike ? classifyMotorcycleCategory(bike) : null; const insight = bike ? `Based on your ${escapeHtml(motorcycleName(bike))} and around ${averageMileage.toLocaleString()} km/day estimated usage, check your ${category?.key === 'scooter' ? 'oil and CVT service' : 'oil and chain service'} next.` : 'Add a motorcycle to receive a maintenance insight based on your real mileage.'; document.getElementById('aiInsight').innerHTML = insight; document.getElementById('askMotoAi').href = `motoai.html?context=${encodeURIComponent(insight)}`; }
async function loadNotificationCount(uid) { try { const snapshot = await getDocs(query(collection(db, 'notifications'), where('uid', '==', uid), where('read', '==', false))); const badge = document.getElementById('notificationBadge'); if (snapshot.size && badge) { badge.textContent = snapshot.size > 99 ? '99+' : snapshot.size; badge.classList.remove('hidden'); } } catch (error) { console.warn('Unread notifications unavailable:', error.message); } }
async function loadDashboard(user) { const uid = user.uid; const [motorcyclesSnapshot, maintenanceSnapshot, repairsSnapshot] = await Promise.all([getDocs(query(collection(db, 'motorcycles'), where('uid', '==', uid))), getDocs(query(collection(db, 'maintenance'), where('uid', '==', uid))), getDocs(query(collection(db, 'repairs'), where('uid', '==', uid)))]); const motorcycles = motorcyclesSnapshot.docs.map((entry) => normalizeRecord({ id: entry.id, ...entry.data() })).filter((item) => item.deleted !== true); const maintenance = maintenanceSnapshot.docs.map((entry) => normalizeRecord({ id: entry.id, ...entry.data() })).filter((item) => item.deleted !== true); const repairs = repairsSnapshot.docs.map((entry) => normalizeRecord({ id: entry.id, ...entry.data() })).filter((item) => item.deleted !== true); const now = new Date(); const monthTotal = repairs.filter((item) => { const date = dateValue(item.date || item.createdAt); return date && date.getMonth() === now.getMonth() && date.getFullYear() === now.getFullYear(); }).reduce((sum, item) => sum + Number(item.cost || 0), 0); const scheduleItems = buildMaintenanceItems(motorcycles, maintenance); const urgent = scheduleItems.filter((item) => item.status !== 'scheduled').slice(0, 3); const nextItem = scheduleItems[0]; document.getElementById('totalBikes').textContent = motorcycles.length; document.getElementById('nextDue').textContent = nextItem?.dueDate ? formatDate(nextItem.dueDate).replace(', 20', ' ') : nextItem ? `${Math.max(0, nextItem.daysUntil)}d` : '--'; document.getElementById('monthTotal').textContent = `₱${monthTotal.toLocaleString()}`; renderStreak(uid); renderInsight(motorcycles); renderUrgent(urgent); renderRecent(repairs); await loadNotificationCount(uid); }
document.getElementById('logoutBtn')?.addEventListener('click', () => signOut(auth));
document.getElementById('notificationBtn')?.addEventListener('click', () => { window.location.href = 'notifications.html'; });
onAuthStateChanged(auth, async (user) => { if (!user) { window.location.href = 'index.html'; return; } const firstName = (user.displayName || user.email?.split('@')[0] || 'Rider').split(' ')[0]; const hour = new Date().getHours(); document.getElementById('userName').textContent = firstName; document.getElementById('greeting').textContent = `${hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'},`; try { await loadDashboard(user); } catch (error) { console.error('Dashboard load failed:', error); } });
